### ISSUE TITLE
Return 200 if no `Range` header is provided

### ISSUE THREAD

**Issue by fixe** [seegno/koa-pagination#15]
From the [HTTP/1.1 Status Code Definitions](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html): 

> 206 Partial Content: The request MUST have included a Range header field (section 14.35) indicating the desired range, and MAY have included an If-Range header field (section 14.27) to make the request conditional.

**Comment by franciscocardoso** [comment]
Closed by https://github.com/seegno/koa-pagination/pull/18.
