### ISSUE TITLE
Support for multiple units

### ISSUE THREAD

**Issue by AdamPflug** [seegno/koa-pagination#22]
Is it possible to support multiple units? The example that comes to mind is if I wanted to paginate a list of items either numerically (items=0-4), or by created date (time=1440015632699-1440015642699).

Maybe I'm trying to shove too much functionality into this though...

**Comment by franciscocardoso** [comment]
Hi @AdamPflug,

Sorry for the delay. 

You can use anything as `unit`, we *don't* have *constraints* on that.
Just make sure that `range` respects all validations. We are deploying a new [validation](https://github.com/seegno/koa-pagination/pull/24) which may not be aligned with your use case.

**Comment by AdamPflug** [comment]
@franciscocardoso I realize can change the unit now, but I want to be able to specify multiple available units that I can pick between in my requests - rather than picking one in the `paginate` middleware config.

I think `paginate` would need to take an array of options objects and also set `this.pagination.unit` to the unit that was specified in the request to be able to support this use case - but there could be other solutions as well.

**Comment by franciscocardoso** [comment]
@AdamPflug Can you please provide an example of an header you wish to use?

**Comment by AdamPflug** [comment]
The missing functionality is the ability to support both the range headers from my original post, on the same route - where based on which unit was specified (items vs time) I would treat the range supplied differently.

One potential issue with that example is something like a date range doesn't have a predetermined number of results, so a better example might be the option to pass either: `oldest=0-4` or `newest=0-4` in the request headers to pull either the first or last items from a set

**Comment by franciscocardoso** [comment]
@AdamPflug Just realize that we weren't exposing the unit.

I'll create a PR to expose `pagination.unit`.

**Comment by AdamPflug** [comment]
Yeah, that solves my problem I think. Thanks#

**Comment by franciscocardoso** [comment]
Thanks for noticing @AdamPflug.
